In [9]:
import numpy as np
import pandas as pd
train_df = pd.read_csv('/Users/eeshitapande/Downloads/titanic_training.csv')

In [10]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(train_df, train_df["Sex"]):
    strat_train_set = train_df.loc[train_index]
    strat_test_set = train_df.loc[test_index]

In [11]:
titanic_train = strat_train_set.copy()

In [12]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Pclass       712 non-null    int64  
 3   Name         712 non-null    object 
 4   Sex          712 non-null    object 
 5   Age          578 non-null    float64
 6   SibSp        712 non-null    int64  
 7   Parch        712 non-null    int64  
 8   Ticket       712 non-null    object 
 9   Fare         712 non-null    float64
 10  Cabin        164 non-null    object 
 11  Embarked     710 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 72.3+ KB


In [13]:
titanic_train = strat_train_set.drop("Survived", axis=1)
titanic_labels = strat_train_set["Survived"].copy()

In [42]:
titanic_train = titanic_train.drop("Ticket", axis=1)

In [43]:
titanic_train = titanic_train.drop("Name", axis=1)

In [44]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Pclass       712 non-null    int64  
 2   Sex          712 non-null    object 
 3   Age          578 non-null    float64
 4   SibSp        712 non-null    int64  
 5   Parch        712 non-null    int64  
 6   Fare         712 non-null    float64
 7   Cabin        164 non-null    object 
 8   Embarked     710 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 55.6+ KB


Cleaning Data 

In [45]:
titanic_train.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   712.000000  712.000000  578.000000  712.000000  712.000000  712.000000
mean    449.637640    2.323034   29.781436    0.546348    0.373596   31.282893
std     256.778217    0.838341   14.628503    1.110283    0.803144   44.377233
min       2.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     231.750000    2.000000   21.000000    0.000000    0.000000    7.895800
50%     454.500000    3.000000   28.000000    0.000000    0.000000   14.456250
75%     667.250000    3.000000   38.000000    1.000000    0.000000   31.275000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")

In [19]:
train_num = titanic_train.select_dtypes(include=[np.number])

In [20]:
train_num.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Pclass       712 non-null    int64  
 2   Age          578 non-null    float64
 3   SibSp        712 non-null    int64  
 4   Parch        712 non-null    int64  
 5   Fare         712 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 38.9 KB


In [21]:
imputer.fit(train_num)

SimpleImputer()

In [22]:
imputer.statistics_

array([4.49637640e+02, 2.32303371e+00, 2.97814360e+01, 5.46348315e-01,
       3.73595506e-01, 3.12828933e+01])

In [23]:
train_num.mean().values

array([4.49637640e+02, 2.32303371e+00, 2.97814360e+01, 5.46348315e-01,
       3.73595506e-01, 3.12828933e+01])

In [24]:
X = imputer.transform(train_num)

In [25]:
train_tr = pd.DataFrame(X, columns=train_num.columns,
                          index=train_num.index)

In [26]:
train_tr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    float64
 1   Pclass       712 non-null    float64
 2   Age          712 non-null    float64
 3   SibSp        712 non-null    float64
 4   Parch        712 non-null    float64
 5   Fare         712 non-null    float64
dtypes: float64(6)
memory usage: 38.9 KB


In [27]:
train_cat = titanic_train.select_dtypes(include=['object'])

In [28]:
train_cat = train_cat[["Cabin", "Embarked"]]

In [29]:
train_cat = train_cat.fillna({"Cabin": "none", "Embarked": "none"})

In [41]:
train_cat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Cabin     712 non-null    object
 1   Embarked  712 non-null    object
dtypes: object(2)
memory usage: 16.7+ KB


In [56]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()
train_cat_encoded = onehot_encoder.fit_transform(train_cat)
train_cat_encoded[:10]

<10x133 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [57]:
train_cat_encoded[:10]

<10x133 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [58]:
train_cat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 788 to 261
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Cabin     712 non-null    object
 1   Embarked  712 non-null    object
dtypes: object(2)
memory usage: 16.7+ KB


In [59]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="mean")),
        ('std_scaler', StandardScaler()),
    ])

train_num_tr = num_pipeline.fit_transform(train_num)

In [60]:
cat_pipeline = Pipeline([
        ('cat', OneHotEncoder())
    ])

train_cat_tr = cat_pipeline.fit_transform(train_cat)

In [61]:
train_num_tr

array([[ 1.32254570e+00,  8.08074478e-01, -2.18556965e+00,
         4.08878121e-01,  2.02647087e+00, -2.41462118e-01],
       [-3.96097035e-01,  8.08074478e-01, -5.39563294e-16,
         4.08878121e-01, -4.65493309e-01, -3.42373002e-01],
       [ 7.02899000e-01,  8.08074478e-01, -5.39563294e-16,
        -4.92425973e-01, -4.65493309e-01, -5.31041404e-01],
       ...,
       [ 1.02246522e+00, -1.57926589e+00, -5.39563294e-16,
        -4.92425973e-01, -4.65493309e-01, -1.06726356e-01],
       [ 1.70007654e-02, -1.57926589e+00,  1.45939592e+00,
         4.08878121e-01, -4.65493309e-01,  1.30386574e+00],
       [-7.31251854e-01,  8.08074478e-01, -2.03369609e+00,
         3.11279040e+00,  2.02647087e+00,  2.35887347e-03]])

In [62]:
train_cat_tr

<712x133 sparse matrix of type '<class 'numpy.float64'>'
	with 1424 stored elements in Compressed Sparse Row format>

In [64]:
from sklearn.compose import ColumnTransformer

num_attribs = list(train_num)
cat_attribs = list(train_cat)

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

In [65]:
titanic_prepared = full_pipeline.fit_transform(titanic_train)

In [66]:
## OrdinalEncoder gave value error: still to investigate why this is so

## Model Selection

In [71]:
## Linear Regression

In [67]:
from sklearn.linear_model import LinearRegression


lin_reg = LinearRegression()
lin_reg.fit(titanic_prepared, titanic_labels)

LinearRegression()

In [70]:
some_data = titanic_train.iloc[:5]
some_labels = titanic_labels.iloc[:5]
some_data_prepared = full_pipeline.transform(some_data)

print("Predictions:", lin_reg.predict(some_data_prepared))

Predictions: [0.49726128 0.16168966 0.38296272 0.41214646 0.30917618]


In [72]:
from sklearn.metrics import mean_squared_error

titanic_predictions = lin_reg.predict(titanic_prepared)
lin_mse = mean_squared_error(titanic_labels, titanic_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.389604867188896

In [73]:
from sklearn.metrics import mean_absolute_error

lin_mae = mean_absolute_error(titanic_labels, titanic_predictions)
lin_mae

0.3106609390876849

In [74]:
## Decision Tree

In [75]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(titanic_prepared, titanic_labels)

DecisionTreeRegressor(random_state=42)

In [103]:
titanic_predictions = tree_reg.predict(titanic_prepared)
tree_mse = mean_squared_error(titanic_labels, titanic_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.0

In [80]:
## Decision tree has clearly overfit the data due to RMSE being 0
## Investigate why decision tree overfits data in both this and housing problems

In [81]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(n_estimators=100, random_state=42)
forest_reg.fit(titanic_prepared, titanic_labels)

RandomForestRegressor(random_state=42)

In [82]:
titanic_predictions = forest_reg.predict(titanic_prepared)
forest_mse = mean_squared_error(titanic_labels, titanic_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.16478152031766866

In [83]:
## SVM

In [102]:
from sklearn.svm import SVR

svm_reg = SVR(kernel="linear")
svm_reg.fit(titanic_prepared, titanic_labels)
titanic_predictions = svm_reg.predict(titanic_prepared)
svm_mse = mean_squared_error(titanic_labels, titanic_predictions)
svm_rmse = np.sqrt(svm_mse)
svm_rmse

0.4384255584812188

In [85]:
## Validation Scores

In [86]:
from sklearn.model_selection import cross_val_score

In [88]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

In [90]:
lin_scores = cross_val_score(lin_reg, titanic_prepared, titanic_labels,
                             scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [0.43333247 0.44345076 0.46328988 0.49408541 0.47216241 0.42892383
 0.40469055 0.47539475 0.43037778 0.50123103]
Mean: 0.4546938869157854
Standard deviation: 0.029771438123540023


In [92]:
scores = cross_val_score(tree_reg, titanic_prepared, titanic_labels,
                         scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)
display_scores(tree_rmse_scores)

Scores: [0.56519417 0.48591266 0.54385168 0.55664994 0.62798583 0.59339083
 0.60514228 0.55664994 0.54385168 0.5814019 ]
Mean: 0.5660030895992232
Standard deviation: 0.03732614657690819


In [94]:
for_scores = cross_val_score(forest_reg, titanic_prepared, titanic_labels,
                             scoring="neg_mean_squared_error", cv=10)
for_rmse_scores = np.sqrt(-for_scores)
display_scores(for_rmse_scores)

Scores: [0.42384647 0.42817442 0.45254367 0.44157529 0.51703379 0.4445634
 0.38201652 0.45143745 0.44334516 0.4874582 ]
Mean: 0.44719943726834277
Standard deviation: 0.03428365070902729


In [95]:
svm_scores = cross_val_score(svm_reg, titanic_prepared, titanic_labels,
                             scoring="neg_mean_squared_error", cv=10)
svm_scores = np.sqrt(-svm_scores)
display_scores(svm_scores)

Scores: [0.47056172 0.44816637 0.50158612 0.52876508 0.5130968  0.4892421
 0.43143673 0.52125608 0.46490295 0.51824677]
Mean: 0.48872607251785166
Standard deviation: 0.031807259314204146


## Precision versus recall - confusion matrix

In [106]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state = 42)

In [107]:
log_reg.fit(titanic_prepared, titanic_labels)
titanic_predictions = log_reg.predict(titanic_prepared)

In [108]:
from sklearn.metrics import confusion_matrix
confusion_matrix(titanic_labels, titanic_predictions)

array([[389,  46],
       [134, 143]])

In [111]:
from sklearn.metrics import precision_score, recall_score
precision_score(titanic_labels, titanic_predictions)

0.7566137566137566

In [112]:
recall_score(titanic_labels, titanic_predictions)

0.516245487364621

In [113]:
from sklearn.metrics import f1_score 
f1_score(titanic_labels, titanic_predictions)

0.6137339055793992

In [ ]:
## Confusion matrix will work here only for classification models and not for regression models
## Theoretically, it has to compare finite number of outcomes with finite predictions / classifications

In [116]:
from sklearn.linear_model import SGDClassifier 
sgd_clf = SGDClassifier(random_state=42)

In [130]:
import numpy as np
titanic_labels_shape = titanic_labels.values.reshape(1, -1)

In [131]:
sgd_clf.fit(titanic_labels_shape, titanic_predictions)
titanic_predictions = sgd_clf.predict(titanic_prepared)

ValueError: Found input variables with inconsistent numbers of samples: [1, 712]